### Delete a person
DELETE http://localhost:3001/api/persons/669d3c803979a2155c942c57


### Get all notes
GET http://localhost:3001/api/persons/



### Post a note
POST http://localhost:3001/api/persons/
Content-Type: application/json


{
    "name": "andreweee",
    "number": "0618"
}



### Delete a person
DELETE https://phonebook-6cqa.onrender.com/api/persons/1


### Get all notes
GET https://phonebook-6cqa.onrender.com/api/persons/



### Post a note
POST https://phonebook-6cqa.onrender.com/api/persons/
Content-Type: application/json


{
    "name": "andrew",
    "number": "0618"
}